version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  windows: circleci/windows@2.4.1
jobs:
  test:
    description: Setup and run application tests
    working_directory: /temp
    docker:
      - image: mcr.microsoft.com/dotnet/sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "WorkSchedule.Web/WorkSchedule.Web.csproj" }}
      - run:
          name: 'Install project dependencies'
          command: dotnet restore
      - save_cache:
          paths:
            - circleci/.nuget/packages
          key: dotnet-packages-v1-{{ checksum "WorkSchedule.Web/WorkSchedule.Web.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet test --no-build --logger "trx"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
  build:
    description: Build application with Release configuration
    working_directory: /temp
    docker:
      - image: mcr.microsoft.com/dotnet/sdk
    steps:
      - checkout
      - run:
          name: 'Build Application according to some given configuration'
          command: dotnet build --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore:
                - /feature.*/
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - master
